### ISSUE TITLE
.scx(t), .vcx(t), etc files belong in git.

### ISSUE THREAD

**Issue by StevenBlack** [cwollenhaupt/foxGitIgnore#2]
Absolutely vital that `.scx/t`, `.vcx/t` etc files be committed to git.

I suspect that including these here makes untenable presumptions about pre-existing tooling?

Or do I misunderstand?

Also: note the typos in code lines 2, 3 and 4.

https://github.com/cwollenhaupt/foxGitIgnore/blob/b76f43ce49cebc679429469a192a4651f34a3288/.gitignore.example#L1-L13

**Comment by cwollenhaupt** [comment]
If you use Visual FoxPro with git you definitely should use extra tooling like foxBin2Prg or TwoFox. Git doesn't have exclusive check outs like TFS or VSS that would prevent changes by others. Moreover, one of the features that makes git stand out is that at its core it manages the relation between commit sets which makes branching not only easy, but an essential feature. You can't work on the same repository with more than one person without eventually having a merge commit. This is different from SVN which manages differences between directories, or CVS/VSS which manage differences between versions of an individual file.

Git does not support merging of binary files. If you have files that are unlikely to change such as assets (images, videos, etc.) then keep them in git. However, if you need to keep binary files in a repository that change as frequently as source code does, git might be the wrong tool for the task.

I agree that the readme should make clear that this .gitignore file is meant for teams or for single developers who work on multiple features in parallel branches. It is not suitable if you work as a single developer and and use git to keep a linear history of your working folder. For this scenario I totally agree that binary files would need to be included, but that is not what this ignore file is meant for.

You are absolutely correct with the typos. Thank you!

**Comment by StevenBlack** [comment]
Not including `.scx`/`.sct`, `.vcx`/`.vct` etc makes zero sense.  I can't imagine a single scenario where this makes any sense.

The acid test is

```
$ git clone  ...foo.git
$ cd foo
```

In VFP, open the `.pjx`, build, and run.

If that doesn't work, out of the box, then you don't "get" git.

**Comment by cwollenhaupt** [comment]
To the contrary... I've worked with multiple developers on enough projects remote and on-site where the repository included all the binaries to know that this approach does not work at all. It's incredible error-prone and time consuming to merge SCX/VCX files with git.
